spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.Oracle10gDialect
#        show_sql: true
        format_sql: true # SQL 예쁘게 보여줌.

logging.level:
  org.hibernate.SQL: debug # SQL logger 출력.
#  org.hibernate.type: trace # 파라미터 보여줌.
